version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:${MONGODB_PASSWORD}@mongodb:27017/twitterxdownload?authSource=admin
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID:-}
      - NEXT_PUBLIC_GOOGLE_ADSENSE_ID=${NEXT_PUBLIC_GOOGLE_ADSENSE_ID:-}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-snnuiabc}
    env_file:
      - .env.local
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  mongodb:
    image: mongo:6.0
    container_name: mongodb-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"  # 只绑定到本地接口
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: twitterxdownload
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongod.conf:/etc/mongod.conf:ro  # 自定义 MongoDB 配置
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
