name = "twitterxdownload"
compatibility_date = "2024-06-24"
pages_build_output_dir = "out"

# Cloudflare D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "twitterxdownload"
database_id = "ea3b3bea-0b8c-44d4-b2c4-1a940fc0576a"  # 需要替换为实际的数据库 ID

# 环境变量
[vars]
NODE_ENV = "production"
CLOUDFLARE_PAGES = "1"
NEXT_PUBLIC_USE_SHARED_DB = "0"
ADMIN_PASSWORD = "snnuiabc"
# 请根据需要设置以下变量
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-SZV4PBRPP4"
# NEXT_PUBLIC_GOOGLE_ADSENSE_ID = "your-adsense-client-id"
# HIDDEN_KEYWORDS = "spam,adult,inappropriate"

# 生产环境配置
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "twitterxdownload"
database_id = "ea3b3bea-0b8c-44d4-b2c4-1a940fc0576a"

[env.production.vars]
NODE_ENV = "production"
CLOUDFLARE_PAGES = "1"
NEXT_PUBLIC_USE_SHARED_DB = "0"
ADMIN_PASSWORD = "snnuiabc"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-SZV4PBRPP4"

# 预览环境配置
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "twitterxdownload"
database_id = "ea3b3bea-0b8c-44d4-b2c4-1a940fc0576a"

[env.preview.vars]
NODE_ENV = "development"
CLOUDFLARE_PAGES = "1"
NEXT_PUBLIC_USE_SHARED_DB = "0"
ADMIN_PASSWORD = "snnuiabc"

# KV 存储绑定（可选，用于缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 存储绑定（可选，用于文件存储）
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "twitterxdownload-assets"
